name: Beauty Salon CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_PREFIX: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-backend

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}

      - name: Build and push Frontend Docker image
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-frontend

      - name: Build and push Frontend Docker image Actions
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-frontend:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-frontend:${{ github.sha }}

      - name: Build and push Data Collector image
        id: meta-collector
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-data-collector

      - name: Build and push Data Collector Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./data-collector
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-data-collector:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-data-collector:${{ github.sha }}